# First, add the API
apiVersion: apps/v1
# This will be the deployment setup
kind: Deployment
metadata:
  # Name your Deployment here
  name: kubetest-dep
  labels:
    # label your deployment
    app: kubetest-app
spec:
  # The number of pods/replicas to run
  replicas: 1            
  selector:
    matchLabels:
    # selector to match the pod
      app: kubetest-app  
  template:
    metadata:
      labels:
      # label your pod
        app: kubetest-app  
    spec:
      containers:
      # Add the container name for Kubernetes
      - name: kubetest 
      # Add the local image name
        image: kubetest 
        # never pull the image policy
        imagePullPolicy: Never
        ports:
        # port for running the container
        - containerPort: 80   
---
# First, add the Service API
apiVersion: v1
# This will be the Service setup
kind: Service
metadata:
  # Your service name
  name: kubetest-src 
spec:
  selector:
    # selector that matches the pod
    app: kubetest-app 
  # type of service
  type: LoadBalancer     
  ports:
  - protocol: TCP 
    # port for exposing the service        
    port: 80
    # portfor exposing the pod             
    targetPort: 80
    # port for exposing the node       
    nodePort: 31110